language: c
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y git debhelper fakeroot
- sudo apt-get install -y libpcap-dev libselinux1-dev
- sudo apt-get install -y binutils-mingw-w64-i686 gcc-mingw-w64 mingw-w64-i686-dev
  mingw-w64-common
- sudo apt-get install -y autoconf automake dh-autoreconf
after_failure:
- cat config.log
script:
- "./autogen.sh"
- git clean -df . && dpkg-buildpackage -b -us -uc
- git clean -df . && export CC=i686-w64-mingw32-gcc && ./autogen.sh --host=i686-w64-mingw32
  --build=$(gcc -dumpmachine)
env:
  global:
  - secure: hOCKM5E4ukXz9FYy0MrHN+0xJe6tFaLuAZliymPxVGNAXtLB3mGTg7gOV3cKQbg6HuWwi0KdwK2eSNxq/+06t1D1GhHVOUpWpwyz+0BUQuKoi0g4SKlQetO9xJp1O9qT1mm4QoX8Lv+LckZl0zQMx+9uuSpbxJCGCEGlGHisV8ONMPei580wctV6oHfl3ytvxtIVBFS0cNLyjYlDGnkWlOPKJJ2zviE+ZJB4uVd2S4eWzPEz4hNcaux8GrgKfs976+UT4yrcUg7vgncCO/VtDo86Fo+WfBTPC6zRT3IGfLJW9DQPpKVi+FrsKIS+vO6LW7Va5TBaVnTQVTPCpgbn2PP9c+HLipp0yyzPVttWvqvmLyqWRtQ80vjwiz/B4/5G4L6kBZZ1CBOVZ1Rw/bMNq2dZLvO10lr2sadTFNTnC8V0GbI9Np0owzKDDuLrHqVglLbSNRFynmrI+/yC58skY40fQO+XpdNievpeEps+scqg/Pukj5bj75YcMoh/3zwTEgcRUq8VpTPt3vcwKZpaIR2S74gJSXfOUq5LN3Y9NNnCqijoyWQxi9zrsOKrOiwesJM4NfazAs2a6lv94M4nXL5wAQ7h+Pxgk7RAUrett/Ghm8QGo1iWvbXFWaaiHkG0I/nXgcOWBN3XkFd6dVekbrP8OdFxntnYYWe6FecpeXA=
addons:
  coverity_scan:
    project:
      name: lnslbrty/ptunnel-ng
    notification_email: matzeton@googlemail.com
    build_command_prepend: autoreconf -i && ./configure
    build_command: make
    branch_pattern: coverity_scan
